"""add raw columns to recipes and ingredients tables

Revision ID: 371d4e3112f2
Revises: 51231d987c70
Create Date: 2026-01-29 16:44:42.787423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371d4e3112f2'
down_revision: Union[str, Sequence[str], None] = '51231d987c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('raw', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('raw', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'raw')
    op.drop_column('ingredients', 'raw')
    # ### end Alembic commands ###
