"""update amount and add unit to ingredients

Revision ID: 51231d987c70
Revises: 6c98ee95b858
Create Date: 2026-01-29 14:30:24.037798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51231d987c70'
down_revision: Union[str, Sequence[str], None] = '6c98ee95b858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('unit', sa.String(), nullable=True))
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingredients', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ingredients', 'unit')
    # ### end Alembic commands ###
